apiVersion: apps/v1
kind: Deployment
metadata: 
 name: primedeployment
spec: 
  replicas: 25
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers:
        - name: primecontainer
          image: nginx
