apiVersion: v1
kind: Service
metadata: 
  name: external-service
spec: 
  selector: 
    app: new-api
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort