apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dotnet-order-api
spec: 
  selector: 
    matchLabels:
      app: dotnet-order-api
  template: 
    metadata: 
      labels: 
        app: dotnet-order-api
    spec: 
      containers: 
        - name: service-api
          image: joaoinvernal/dotnet-order-api:v1.0.0
          ports: 
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          imagePullPolicy: Always 
          env: 
            - name: Mongo__Host
              value: "mongo-service"
            - name: Mongo__User 
              value: "mongouser"
            - name: "Mongo__Password"
              value: "mongorootpwd"
            - name: Mongo__Port
              value: "27017"
            - name: Mongo__DataBase
              value: "admin"