apiVersion: v1
kind: Service
metadata: 
  name: api-service
spec: 
  selector: 
    app: dotnet-order-api
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30081
      name: https
  type: NodePort

## Access the API from K3d NodePort Service ( Bind: 30080 --> 8082 )
## > http://localhost:8082/swagger/