apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-color-deploy
spec: 
  selector: 
    matchLabels: 
      app: nginx-color
  template: 
    metadata: 
      labels: 
        app: nginx-color
    spec: 
      containers: 
        - name: color-nginx
          image: kubedevio/nginx-color:green


 ## $ kubectl create namespace green-space
 ## > kubectl apply -f Green-deployment.yaml -n green-space 

 ## Existe uma outra forma para enviar o deploy, com o namepsace
 ## especificado diretamente para o arquivo do manifeso.
 ## Adicionar o campo namespace para o metadata. Exemplo: 

 ## metadata: 
 ##   name: name
 ##   namespace: nome-do-namespace